openapi: 3.0.3
info:
  title: API Authentication
  version: 1.0.0
servers:
- url: http://localhost:5000/rest/authentication-api/v1.0
tags:
- name: Login
paths:
  /login:
    post:
      tags:
      - Login
      summary: Authentication
      description: Autenticacion de usuario.
      operationId: loginPOST
      requestBody:
        description: Usuario a ser creado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestLogin'
        required: true
      responses:
        "200":
          description: Inicio de sesi贸n exitoso
          content: {}
        "404":
          description: Credenciales no existentes
          content: {}
        "500":
          description: 'Error de inicio de sesi贸n '
          content: {}
      x-codegen-request-body-name: RequestLogin
      x-swagger-router-controller: Login
  /login/recovery-password:
    post:
      tags:
      - Login
      summary: Recovery
      description: Recuperacion de usuario.
      operationId: loginRecovery_passwordPOST
      requestBody:
        description: Recuperaci贸n de clave
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/RequestRecoveryPassword'
        required: true
      responses:
        "200":
          description: "Recuperaci贸n de clave exitoso, fue enviada a tu correo"
          content: {}
        "404":
          description: Usuario no encontrado
          content: {}
        "500":
          description: Error de recuperar clave
          content: {}
      x-codegen-request-body-name: RequestRecoveryPassword
      x-swagger-router-controller: Login
  /login/change-password:
    post:
      tags:
      - Login
      summary: Change
      description: Cambio de clave.
      operationId: loginChange_passwordPOST
      requestBody:
        description: Cambio de clave
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/RequestChangePassword'
        required: true
      responses:
        "200":
          description: Cambio de clave exitoso
          content: {}
        "404":
          description: Usuario no encontrado o clave incorrecta
          content: {}
        "500":
          description: Error de Cambio de clave
          content: {}
      x-codegen-request-body-name: RequestChangePassword
      x-swagger-router-controller: Login
components:
  schemas:
    RequestLogin:
      type: object
      properties:
        user:
          type: string
        password:
          type: string
    ResponseLogin:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        data:
          type: object
          properties: {}
    RequestRecoveryPassword:
      type: object
      properties:
        user:
          type: string
    RequestChangePassword:
      type: object
      properties:
        user:
          type: string
        password:
          type: string
        passwordnew:
          type: string
